#!/bin/bash

DIR=nagiosxi
DLDIR=nagiosxi
FILE=xi-latest.tar.gz

# Check whether we have sufficient privileges
if [ $(id -u) -ne 0 ]; then
    echo "This script needs to be run as root/superuser." >&2
    exit 1
fi
    
if ! which wget &>/dev/null; then
	if [ `command -v yum` ]; then
		yum install wget -y
	else 
		apt-get -y install wget
	fi
fi

cd /tmp
echo "check if /tmp/nagiosxi exists"
if [ -d /tmp/$DIR ]; then
    rm -rf /tmp/$DIR
fi

echo "Downloading latest Nagios XI release"
wget https://assets.nagios.com/downloads/$DLDIR/$FILE -O /tmp/$FILE
tar xzf /tmp/$FILE
cd /tmp/$DIR
chmod +x ./fullinstall
./fullinstall -n


or

yum update -y
yum install wget && yum install curl -y
curl https://assets.nagios.com/downloads/nagiosxi/install.sh| sh

or

https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbGlsVU5UcUNsSnZIRzB0SEx1T2QyY1V1SnpMd3xBQ3Jtc0tsMnlTdElGUmk5TTZ4RVdsOFpKRjdUS3gwbFF4Ml9ZWDlwVTBOVlhLeE1oWl81Wk9DTE9sMDByQUJrYlBLR1E1dTh6Vng5emhkRFNvUFNfNU50R2U5eDU1R25YYnV5SzFVakdPMF9heFEyNy1lS2hiVQ&q=https%3A%2F%2Fassets.nagios.com%2Fdownloads%2Fnagiosxi%2Finstall.sh




